server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
jwt:
  secret: febnsdl1324r1352514245123rfndlsasdfnk124135135132nlke31124124
